import { Inter } from 'next/font/google';
import '@styles/globals.css';
import Providers from './provider/prodiver.js';

export const metadata = {
  title: "Task Management",
  description: "Generated by next and laravel",
};

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
